### ISSUE TITLE
Calling js method onDone failed, on line 18

### ISSUE THREAD

**Issue by EvenHus** [bradmartin/nativescript-texttospeech#11]
Hi, 
When speak is finished on android, my app crashes and i get `TypeError: Cannot read property 'finishedCallBack' of null` 

Here's my code

`speak(text: string): Promise<any> {
    return new Promise((resolve, reject) => {

      const speakOptions: SpeakOptions = {
        text: text,
        language: this._language,
        speakRate: 0.48,
        finishedCallback: () => {
          resolve();
        }
      };

      this._TTS.speak(speakOptions);
    });
  }`

Any idea what may cause this?

**Comment by bradmartin** [comment]
Not sure without debugging it or running but I would guess it's an issue because the TTS `speak` method already returns a promise and you're wrapping it in a promise and resolving in the callback. So you could just use
``` typescript
const speakOptions:....
this._TTS.speak(speakOptions).then((result) => { 
   // do something here after the speak resolves 
});
```

**Comment by EvenHus** [comment]
Hi again, 
I changed some of my code and here are som further explaining. In the code below i set up texttospeech in a service that i use around my app. 


import {Injectable} from '@angular/core';
import {device} from 'platform';
import {TNSTextToSpeech, SpeakOptions} from 'nativescript-texttospeech';

```
@Injectable()
export class TextToSpeechService {
  private _TTS: any = new TNSTextToSpeech();
  private _language: string;

  constructor() {
    this._setTTSLanguage();
  }

  speak(text: string): void {
      const speakOptions: SpeakOptions = {
          text: text,
          language: this._language,
          speakRate: 0.48
      };

      this._TTS.speak(speakOptions).then(() => {
          console.log("Done speaking");
      }, (err) => {
         console.log("***ERROR***", err);
      });
  }

  private _setTTSLanguage(): void {
    const lang = device.language.split('-')[0];

    switch (lang) {
      case 'nb':
        this._language = 'nb-NO';
        break;
      default:
        this._language = 'nb-US';
    }
  }
}

```
I then import the service in my components around the app, here is an example of usage of the service. 
```
speak(textsToRead: any[], button: Button): void {
    const text: string[] = [];
    textsToRead.map(part => {
      if (part.isDate) {
        text.push(this._datePipe.transform(part.text, 'EEEE d MMMM'));
      } else if (part.isTime) {
        if (part.all_day) {
          text.push(this._translate.instant('All Day') + ': ');
        } else {
          text.push(this._translate.instant('At') + ' ' + this._datePipe.transform(part.text, 'HH:mm') + ': ');
        }
      } else {
        text.push(part.text);
}
    });
    this._tts.speak(text.join(' '));
  }
```
I still get this message when done speaking: 
TypeError: Cannot read property 'finishedCallBack' of null

Thank you so much for any help :)

**Comment by briandilley** [comment]
I see this error in my crash reports too - haven't been able to figure it out.  Defining a function for finishedCallback doesn't seem to work.

**Comment by bradmartin** [comment]
The demo app seems to work properly. However, I've added a null check on the `lastOptions` https://github.com/bradmartin/nativescript-texttospeech/blob/master/texttospeech.android.ts#L24 to ensure it and the callback are defined so the error should not be throwing anymore. If it still is an issue please let me know and we can look into it further.
