### ISSUE TITLE
how to define the voice ?

### ISSUE THREAD

**Issue by sunpasup** [bradmartin/nativescript-texttospeech#19]
i am using this Text to Speech for my Voice Bot, Some Phones Giving me Male Voice, and Some Phones Giving me female voice, how can i fix it to one Particular Voice.??

**Comment by lsowmya** [comment]
Facing the same issue.
Is there any possibility to restrict only to Female Voice ?

**Comment by bradmartin** [comment]
Can one of you call `getAvailableLanguages` method and provide the output here for the devices you're using? Supposedly if the device has support for male/female it will be listed in the available languages. At least on Android. I haven't looked at iOS APIs.
