### ISSUE TITLE
Can't speak Polish language in real device

### ISSUE THREAD

**Issue by Arystosedes** [bradmartin/nativescript-texttospeech#23]
Hi, there is a problem with polish speaking in android real device. I have nativescript - angular app, and in an android SDK emulator everything works properly, but not in the real device. On real device Polish words are spoken with English accent.

    this.synth.speak({
      text: 'przykład',
      speakRate: 1.0,
      volume: 1.0,
      language: 'pl',
      finishedCallback: function () {},
    });

Any idea why is the difference between the android SDK emulator and the real device with android?

**Comment by bradmartin** [comment]
Does the device has the same SDK installed? My first guess is the device doesn't have any knowledge of Polish for text to speech so it falls back to `en-US`. I would suggest searching for information on the device and how to determine if the specific android device does support polish speech and go from there.

let me know what you find. Thanks.

**Comment by bradmartin** [comment]
Oh just noticed you have `language` as an option, try using `locale` instead. See if that helps
