### ISSUE TITLE
First sound playing is long to start

### ISSUE THREAD

**Issue by GrEg00z** [bradmartin/nativescript-texttospeech#7]
After every startup of my app, I have to wait maybe 10 secondes before the first sound start to play, when using :

`this.TTS.speak(speakOptions);`

After the first sound finished, all others calls to **this.TTS.speak** are directly played.

I've tried to re-install the app but nothing changes

**Comment by bradmartin** [comment]
Initializing the synthesizer takes some time and varies on device
capabilities. Are you playing the sound at app start? Or during some user
interaction? If with some user interaction you should create an instance of
the synthesizer before calling speak(). One solution might be to initialize
it in a page navigation event and then just reuse that instance when
needed. You could also try initializing on app start and attaching your
instance to global and reuse it across your app. Let me know if that makes
any sense or not. :)

**Comment by GrEg00z** [comment]
Yes it makes sense :)

I'm playing the sound after user interaction, on a tap event action.

I'm using nativescript with angular, and I created an 'angular' service in my app that instanciate TNSTextToSpeech , which is initialized after app start (declared as provider in my app.module file).

So I use only one instance of TNSTextToSpeech in my app, which is instanciate long time before I call **this.TTS.speak** (method play() in my service).
Systematically, the time to wait is about 10-12 seconds

Here the service I created :

```
import { Injectable }             from '@angular/core';
import { TNSTextToSpeech, SpeakOptions } from 'nativescript-texttospeech';

@Injectable()
export class SpeakerService {

  TTS : TNSTextToSpeech;
  constructor() {
      this.TTS = new TNSTextToSpeech();
  }

  play(text : string) {
    let speakOptions: SpeakOptions = {
        text: text, /// *** required ***
        speakRate: 1.0, // optional - default is 1.0
        pitch: 1.0, // optional - default is 1.0
        volume: 1.0, // optional - default is 1.0
        language: "fr-FR",  // optional - default is system language,
        finishedCallback: () => {
          console.log("We have finish to read text");
        } // optional
    }
    this.TTS.speak(speakOptions);
  }
}
```

**Comment by bradmartin** [comment]
Can you confirm, maybe with some console.logs() in the constructor the timing before/after the `this.TTS = new...` and see how long it's taking and when it's being initialized? I'd also try logging out `this.TTS` inside the `play` method and see if it's the same instance the constructor creates. They should log the same value if so.

**Comment by GrEg00z** [comment]
Yes it's well instanciate during app start, it takes no time.
Also there is no callback or others ways (like observale or promise) to detect that the synthesizer is ready to be used, asynchronously.

I've just added this to detect that TNSTextToSpeech is ready :

```
constructor() {
      console.log("init SpeakerService")
      this.TTS = new TNSTextToSpeech();
      console.log("end init SpeakerService", JSON.stringify(this.TTS))
  }
```

I've checked **this.TTS** inside play method, it also have the same instance as constructor 

I can also confirm that when I add this inside **finishedCallback** function (in **play** method) :

```
this.TTS.destroy();
this.TTS = new TNSTextToSpeech();
```
Then every next call to **play** method take also 10-12s to play

**Comment by bradmartin** [comment]
Don't destroy unless you want to init a new instance. Is that what you
want? Destroy will destroy the instance and free up memory on device. So
only use it when you will no longer use the module. As for my test app I
did for egghead last month on my Droid turbo 2 it takes about 2seconds to
init the synthesizer and then speak method is near instant when using that
instance at any time later.

**Comment by GrEg00z** [comment]
Yeah it's not also what I want destroy the instance
It was just for yours informations and help for debug.

At some application startup, it plays the first sound directly with no waiting time.
But most of time it's 10s to play

**Comment by rkhayyat** [comment]
I confirm the long delay of instanciation as it happened with GrEg00z ( arround 10-12 sec), and by the way, only when I use the english language en-USA, it is much faster in instanciation

**Comment by GrEg00z** [comment]
Yes the same for me, with english language it's very fast on first playing

**Comment by bradmartin** [comment]
On android it's a second or two to init for the device I have. I don't have any iOS devices to test the result there. Sorry. I don't have time to dig in and see what can be done to improve this. If someone wants to help I can answer any questions they might have. I would first start with viewing official documentation on the native speech synthesizers, finding an example from apple and google on using it and then lets make sure we implement it the same way. Then we can look at adding a NS background thread (worker) to the init and see if that's something we can implement with this plugin and run the speech synth on a worker thread 👍

**Comment by bradmartin** [comment]
https://github.com/bradmartin/nativescript-texttospeech#tip
